### PR TITLE
Newlines

### PR DESCRIPTION
**Pull request by hmaarrfk**
I was trying to understand your message protocol. And got stuck on `\r\n`. 

It seems Arduino uses `\r\n` in a pretty fundamental way.

I did all these changes, but I don't think it is worth pushing them in because it might introduce bugs.

I'll let you decide if you want to test them.
I got stuck at compiling 

```
C:\Users\Mark\AppData\Local\Temp\arduino_build_537843\sketch\sciwing.cpp:30:33: fatal error: src/TLC5955/TLC5955.h: No such file or directory

compilation terminated.

Error compiling for board Teensy 3.2 / 3.1.
```

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Even if you wanted to implement this, this isn't worth doing on your side.

The functions should be added to Arduino and Teansy.

Then you can simply to a search and replace.

I don't know of an other way to overwrite their functions in C++ an "easy way"

Follow: [Arduino PR #7364](https://github.com/arduino/Arduino/pull/7364)
[Teasy PR #273](https://github.com/PaulStoffregen/cores/pull/273)

**Comment by zackphillips** [comment]
I see - yes, I think we should conform to '/n' instead of '/r/n'. But really we should have a constant expression serial_line_ending which can be defined in the code itself. I will try to do this tonight and see where it takes me.

W.R.T. compilation, TLC5955 is a submodule, so you'll need to run 
`git submodule init`

followed by

`git submodule update`

to check out the library. I've recently added a small script (submodules.sh) which will execute these comments for you so you don't have to remember them.

**Comment by zackphillips** [comment]
I just finished removing all println statements in favor of printf and print statements which use the const char SERIAL_LINE_ENDING defined in illuminate.h:

`// Serial line ending
static const char SERIAL_LINE_ENDING[] = "\n";

// Serial command termiator
static const char SERIAL_COMMAND_TERMINATOR[] = "-==-";`

Hopefully this solves this issue, it was a lot of work but only needs to happen once...

**Comment by hmaarrfk** [comment]
Ah, thanks for the submodule trick.
I thought you might be using that.

Arduino doesn't seem to be interested in my PR, so maybe your strategy is the only way. `println` is so engrained in the arduino API that I think it is really necessary to provide a switch. I'm sure some of their examples have the same problems.

With regard to newlines, the python `strip()` function removes all surrounding whitespace (`\r` included) by default.

**Pull request closed without merging**
